/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LMap {
        "center": string;
        "currentLocation": string;
        "currentLocationIconUrl": string;
        "iconUrl": string;
        "locations": Array<[number, number]>;
        "maxZoom": string;
        "minZoom": string;
        "tileLayerUrl": string;
        "zoom": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLLMapElement extends Components.LMap, HTMLStencilElement {
    }
    var HTMLLMapElement: {
        prototype: HTMLLMapElement;
        new (): HTMLLMapElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "l-map": HTMLLMapElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface LMap {
        "center"?: string;
        "currentLocation"?: string;
        "currentLocationIconUrl"?: string;
        "iconUrl"?: string;
        "locations"?: Array<[number, number]>;
        "maxZoom"?: string;
        "minZoom"?: string;
        "onMessage"?: (event: CustomEvent<any>) => void;
        "tileLayerUrl"?: string;
        "zoom"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "l-map": LMap;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "l-map": LocalJSX.LMap & JSXBase.HTMLAttributes<HTMLLMapElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
